### ISSUE TITLE
Blog Posts

### ISSUE THREAD

**Issue by ximsce** [codefordenver/Circular#154]
To improve recruitment and generate donor interest, create some basic blog posts for the project to put on the Code for Denver website

**Comment by chompasina** [comment]
Questions: how long? what topic? or is it just a history of our team?

**Comment by JasminBarco** [comment]
Maybe something like this?
Blog post 1

The Denver RE:Imagine team is working on styling the live webpage. Check out our latest wireframe here: https://xd.adobe.com/view/a48a6643-152a-4619-96b9-c44f6f610679/screen/b04184d8-7c2c-4049-8a18-0c558cf1b9af/Campaign-Page-Home

**Comment by ximsce** [comment]
That sounds good to me! @wdoug or @dviramontes who should we send blog posts to?

**Comment by dviramontes** [comment]
@ximsce - I just made you an account over at http://codefordenver.org/login
I'll dm you your creds :)

**Comment by dviramontes** [comment]
Thanks for posting @ximsce !
