### ISSUE TITLE
Add new address -signing name (non-auth)

### ISSUE THREAD

**Issue by chompasina** [codefordenver/Circular#174]
(lower priority) This story implements the signing name with non-authentication functionality of the following feature:

After I enter my building's address, I see a popup that says "Sign your name to show your support." I can sign with Google or Facebook, or there are fields First Name, Last Name, Email Address, Add a Comment. There are two checkboxes that are checked by default: "Keep me updated on the status of this recycling request" and "Publicly display my name on this page". There is also a statement "By signing you accept the Terms of Agreement and Privacy Policy". And a button that says "Sign to show your support"

**Comment by wdoug** [comment]
I'm skeptical that we should ever do this as it would require we figure out how to verify identity outside of Oauth, and I'm not sure if we could even do that

**Comment by hoop71** [comment]
Closing this ticket, doesn't fit app flow anymore.
