### ISSUE TITLE
Bug - error message rendering when creating a new campaign

### ISSUE THREAD

**Issue by scottfirestone** [codefordenver/Circular#182]
Related to #160. To reproduce:

1) Search for an address where a campaign already exists (or create a campaign and then search for its address)
2) When the results come up, choose 'None of these...'
3) You should see the error message. Return to home.
4) Search for an address with no active/nearby campaigns. Create a new campaign.
5) The error message will appear on the form.

**Comment by dannyradden** [comment]
What branch does this happen on? When I got to step 5 there was no error message on the form.

**Comment by scottfirestone** [comment]
This is happening on master.

**Comment by scottfirestone** [comment]
![Screen Shot 2017-11-06 at 6.57.40 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5693f9a12432bb0e00502bda/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76226454f56b7191a37ef1172c4f5b5f5ecc3c4a4356bcbbd671f3e57862804e0eea82690b20c03910ffeb8017b600be208b4786e7b48b45d2f42f67b6d5db1063474f4dcbed5727a19141c95df74be14c5cac143f64ee7f2431.png)

**Comment by scottfirestone** [comment]
Never mind - notes above were for an old version. It looks like the app has changed in such a way that this error can no longer be produced. Closing this issue.
