### ISSUE TITLE
Create new routes/links for Navbar

### ISSUE THREAD

**Issue by chompasina** [codefordenver/Circular#194]
Probably need to confirm with Jasmin first:
- Why (previously About(?))
- Tools (what does this mean @Casey1449?)
- My Campaign (will this recognize a user via cookies @Casey1449 ?)
- Who We Are (Not sure if we want this to explain about the collaboration between Code for Denver and EcoCycle or just EcoCycle...) 

![image](https://user-images.githubusercontent.com/15034459/32407226-76be5bba-c14b-11e7-8ce7-9e0e7301fbd4.png)

**Comment by JasminBarco** [comment]
* Why (previously About(?))
Denver recycles 18% and composts 2%. Leading cities like San Fransisco are diverting as high as 80% while Denver is falling behind with only diverting 20%. 

Denverites believe they can do better! As a tenant in a Denver Multi-Family Complex (MFC) with 8 or more units, your property manager or landlord is NOT required to provide you recycling or composting waste services. Many tenants in Denver have resorted to illegally dumping their recyclables in a neighbor’s recycling dumpster, or driving out of their way to a transfer station or parent’s home. 

It’s time to organize and request better waste services from property managers in Denver. There’s power in numbers, by participating and gathering momentum with the Denver Recycling Request tool, property managers know this is important to you and your neighbors. 

* Tools (what does this mean @Casey1449?)
-Recycling Request Tool Flier 
*PDF, ready Feb 16* 

-City of Denver Business and Multi-Family Recycling
https://www.denvergov.org/content/denvergov/en/trash-and-recycling/recycling/business-and-multi-family-recycling.html

-How to Get Recycling Bins in Your Apartment Complex
https://ohmyapt.apartmentratings.com/how-to-get-recycling-bins-in-your-apartment-complex.html

-How to Get Recycling Bins in Your Apartment Complex
https://blog.rent.com/how-to-recycle-when-your-apartment-complex-doesnt/ 

* My Campaign (will this recognize a user via cookies @Casey1449 ?)
Get rid of “My Campaign”

* Who We Are (Not sure if we want this to explain about the collaboration between Code for Denver and EcoCycle or just EcoCycle...)- we should have both! (JB) 
Code for Denver is volunteer-driven, community outreach that improves people’s lives through technology.
https://www.codefordenver.org/

Eco-Cycle is a Zero Waste non-profit based in Boulder Colorado. They started working in Denver in 2016 as a commitment at the Denver Sustainable Summit to increase Denver’s diversion rate to 34%. 
ecocycle.org
