### ISSUE TITLE
Make search bar stick to the top of the nav bar when in mobile view

### ISSUE THREAD

**Issue by chompasina** [codefordenver/Circular#197]
When active:
![image](https://user-images.githubusercontent.com/15034459/32407354-3ddf8efc-c14d-11e7-926a-df12231fa740.png)
When inactive:
![image](https://user-images.githubusercontent.com/15034459/32407366-5764e8a4-c14d-11e7-8f2c-9de893b47357.png)

**Comment by hoop71** [comment]
Closing. no long fits app flow.
