### ISSUE TITLE
Update "you're the first" page

### ISSUE THREAD

**Issue by chompasina** [codefordenver/Circular#199]
![Screen Shot 2017-11-20 at 5.20.44 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/577c1be0dd37d913008c8147/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76226456f36b7191a37df1102b4f5b5b5ecc3c4a4356bcbbd671f3e57862804e0eea82690b20c03910ffeb8017b600be208b4786e7b48b45d2f42f67b6d5db1063474f4dcbed5727a19e41c95df74ae34f56a2153666e5762431.png)

bullet pointed font styling:
![Screen Shot 2017-11-20 at 5.21.18 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/577c1be0dd37d913008c8147/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76226456f36b7191a37df1102a4f5e575ecc3c4a4356bcbbd671f3e57862804e0eea82690b20c03910ffeb8017b600be208b4786e7b48b45d2f42f67b6d5db1063474f4dcbed5727a19e41c95df74ae34f56a21a3e67e1732431.png)

**Comment by ximsce** [comment]
what's the status on styling this out?
