### ISSUE TITLE
Add chat/comment form to campaign pages

### ISSUE THREAD

**Issue by chompasina** [codefordenver/Circular#206]
(so will need to create a new comments table with a relationship to the signature)

![image](https://user-images.githubusercontent.com/15034459/32407579-bce45d7e-c150-11e7-9e11-5d31a47001a8.png)

**Comment by ximsce** [comment]
https://www.npmjs.com/package/node-comment might be simple enough to add in quickly without having to deal with disqus

**Comment by ximsce** [comment]
consider this story a spike for building a very simple chat/comment thread functionality into the app (potentially research plugins, but try not to commit to one in particular until reviewing with stakeholders)

**Comment by ximsce** [comment]
consider this story a spike for building a very simple chat/comment thread functionality into the app (potentially research plugins, but try not to commit to one in particular until reviewing with stakeholders)

**Comment by ximsce** [comment]
I haven't been able to find any plug and play modules for react that don't use disqus. In my experience, disqus is more trouble than it's worth, so I looked at some tutorials that would help us roll our own comment system. The following is a list of implementations that we could potentially stitch together:

* https://www.npmjs.com/package/node-comment + https://github.com/magnumjs/mag.js/blob/master/examples/tutorials/react-comments-component.md / https://medium.com/@gsuppy/coding-an-interactive-comment-box-with-react-js-50d7d20587d8
* http://rationalappdev.com/implementing-comments-with-react-native-and-nodejs/
