### ISSUE TITLE
Add description of project to Readme

### ISSUE THREAD

**Issue by wdoug** [codefordenver/Circular#229]

**Comment by JasminBarco** [comment]
Denver recycles 18% and composts 2%. Leading cities like San Fransisco are diverting as high as 80% while Denver is falling behind with diverting 20%. 

Denverites believe they can do better! As a tenant in a Denver Multi-Family Complex (MFC) with 8 or more units, your property manager or landlord is NOT required to provide recycling or composting waste services. Many tenants in Denver have resorted to illegally dumping their recyclables in a neighbor’s recycling dumpster, or driving out of their way to a transfer station or parent’s home. 

It’s time to organize and request better waste services from property managers in Denver. There’s power in numbers, by participating and gathering momentum with the Denver Recycling Request tool, property managers know this is important to you and your neighbors.
