### ISSUE TITLE
Update background fill for across site

### ISSUE THREAD

**Issue by chompasina** [codefordenver/Circular#240]
(I don't think this is covered anywhere but the background everywhere should have these settings:
<img width="1304" alt="screen shot 2017-11-20 at 5 17 54 pm" src="https://user-images.githubusercontent.com/15034459/33048189-d5222d6c-ce16-11e7-897b-879b3f33e4b1.png">

**Comment by hoop71** [comment]
removed linear gradient and replaced with solid fill #0c6f91

New Version: 
body {
   background: #0c6f91;
}

Old Version: 
body {
   background: linear-gradient(to bottom,  #164c5f);
}

**Comment by hoop71** [comment]
@wdoug it was such a small change we were going to incorporate it with other changes that Alyssa is making.
