### ISSUE TITLE
Can't add letter on Create New Campaign form

### ISSUE THREAD

**Issue by JasminBarco** [codefordenver/Circular#262]
https://denver-reimagine.herokuapp.com/new-campaign/address 

Apartment number only allows numbers and no letters. What if someone lives in "4B"?

**Comment by TheBrooks** [comment]
The address for the campaign is provided by the google API.  
For recycling campaign the building itself should be enough information to create an accurate enough campaign.  
Closing this issue.  If users find this feature necessary after launch then it should be reopened
