### ISSUE TITLE
Google OAUTH directing to blank page

### ISSUE THREAD

**Issue by JasminBarco** [codefordenver/Circular#273]
It happened on my laptop, but not on Willy's laptop...
It's navigating to `/auth/google` instead of Google's OAUTH

**Comment by ximsce** [comment]
@JasminBarco is this still an issue? I think we have keys on the production heroku for oauth now

**Comment by JasminBarco** [comment]
Not sure what this issue is even about! Let's check it out on Thursday? @ximsce

**Comment by ximsce** [comment]
I won't be there on Thursday, but if you can navigate through the production heroku site and sign a campaign then I think this can be resolved.

**Comment by scottfirestone** [comment]
@ximsce @JasminBarco Looks like this was closed; I'm still having issues on production, seeing the 404 when trying either facebook or google buttons:
![Screen Shot 2018-03-19 at 6.54.19 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5693f9a12432bb0e00502bda/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206455fa6b7191a37ef1172f4f5e565ecc3c4a4356bcbbd671f3e57862804e0eea82690b20c03910ffeb8017b600be208b4786e7b48b45d2f42f67b6d5db1063474f4dcbed5727a19e41c95df44ae44d52a7133162ef7f2431.png)
