### ISSUE TITLE
Style signature drop-down on campaign page

### ISSUE THREAD

**Issue by JasminBarco** [codefordenver/Circular#274]
when seeing a campaign page, I see a drop-down bar for the "signatures"

**Comment by wdoug** [comment]
This should be fixed for mobile as well!

**Comment by hoop71** [comment]
Just made some progress here. Will need some help implementing this as auth / signature state changes, please. 

<img width="1278" alt="screen shot 2018-03-06 at 17 23 43" src="https://user-images.githubusercontent.com/25015764/37112834-de8566a6-2200-11e8-86ae-64664ce9f45b.png">
<img width="336" alt="screen shot 2018-03-07 at 12 11 56" src="https://user-images.githubusercontent.com/25015764/37112840-e1097d18-2200-11e8-84fa-cb3ea1e0894d.png">
<img width="332" alt="screen shot 2018-03-07 at 12 12 04" src="https://user-images.githubusercontent.com/25015764/37112847-e29f2506-2200-11e8-8be5-27b7608cd080.png">
