### ISSUE TITLE
Handle dummy data

### ISSUE THREAD

**Issue by wdoug** [codefordenver/Circular#275]
Right now there is a bunch of test data on denver-reimagine.herokuapp.com. Let's delete this and only do testing on denver-reimagine-state.herokuapp.com so we can start using this for actual campaigns.

Acceptance Criteria:
- dev database can be wiped with yarn command
- dev database can be seeded with test campaigns and signatures
- prod database can be wiped & initialized in a manual fashion (not sure how to auth this through the central setup)

**Comment by hoop71** [comment]
This is shared with 345. The Dev db is still shared. Future improvements: setup a local Mongo-In-Memory db for local tests.

**Comment by hoop71** [comment]
Creating new ticket for Firebase!
