### ISSUE TITLE
Build out "Property Manager FAQ page"

### ISSUE THREAD

**Issue by JasminBarco** [codefordenver/Circular#280]
When I go to the Denver Recycling Request Tool homepage, I scroll down past the address input and see two "more info" options. On the left, "learn more" for information on Denver's Recycling Rate and on the right and tenants, and on the right a  "tips and resources" link under the "property managers" section.

Second Property Manager FAQ link to page exists under "Tools" on top right area of the website.

**Comment by JasminBarco** [comment]
![Screen Shot 2018-02-22 at 19.39.41.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/584619e37a5c7e1300b983de/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216456f16b7191a379e60c2858415b4fbe5d4a1f06a3a3dc78e2a436628f5b58e985395970c76e42aeb08b1ebb01ba28881e8db7b59850d2aa6c7bb3d4d216744b470a83ed5c3daa984ec951f54ee2485ca31a3e64f43b.png)

**Comment by JasminBarco** [comment]
"Tips for Purchasing service" **Tab**
1. Check your current contract
2. See list of haulers offering recycling in your area
3. Obtain different bids

"Going through the bid process" **Tab** 
1. Have your address ready
2. Know how many bins, and what sizes you currently have 
3. Establish pick-up frequency
![Screen Shot 2018-02-22 at 19.42.45.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/584619e37a5c7e1300b983de/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216456f16b7191a379e60c2f53415b4bbe5d4a1f06a3a3dc78e2a436628f5b58e985395970c76e42aeb08b1ebb01ba28881e8db7b59850d2aa6c7bb3d4d216744b470a83ed5c3daa984ec951f54ee24555a2173261f43b.png)

**Comment by JasminBarco** [comment]
Minus the Calculator estimator
[Screen Shot 2018-02-22 at 20.27.15.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/584619e37a5c7e1300b983de/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216456f16b7191a37aef0c2956415e4bbe5d4a1f06a3a3dc78e2a436628f5b58e985395970c76e42aeb08b1ebb01ba28881e8db7b59850d2aa6c7bb3d4d216744b470a83ed5c3daa984ec951f54ee7495ca11b3f6bf43b.png)

**Comment by TheBrooks** [comment]
@JasminBarco do you have a higher resolution file for the "Solid Waste &..." file picture.  the one here is too  pixelated for the production site.
