### ISSUE TITLE
update home base design

### ISSUE THREAD

**Issue by TheBrooks** [codefordenver/Circular#288]
[home_page.pdf](https://github.com/codefordenver/Circular/files/1773618/home_page.pdf)

**Comment by TheBrooks** [comment]
@JasminBarco Hey Jasmin could you provide me the text samples that should go in each of these 4 steps? thank you!

**Comment by JasminBarco** [comment]
Hey Ryan! 
1.  Create and share your Multi-family Complex (MFC's) campaign page with your neighbors. 
2.  Voice and organize your support  
3. Request recycling services from your landlord by sharing your building's campaign page
4. Recycle and live in a more  sustainable building

**Comment by JasminBarco** [comment]
Thank you!

**Comment by TheBrooks** [comment]
Thanks!  i think in the future it would be good to add a few sentences per(the page looks better with a larger size text chunk) but this is good for now
