### ISSUE TITLE
Design- "optional info" window

### ISSUE THREAD

**Issue by JasminBarco** [codefordenver/Circular#290]
When I create a campaign, an "optional info" window pops up.
![Create Campaign - Step 2.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/584619e37a5c7e1300b983de/125516c66e82c728ace21e0d46cb869f229686e9ace8b253a554f79a690b67403d01b36b22c7af6aaf50740b0a0c0abe4b4a5a43affddd7fa0b23d23d95e03e4d0695f74ce3e40a4b98b0da313f871d51bdaebe5c01982fa3737e682854e3b1c051b89fb5b35a39d48cb4abb.jpg)

**Comment by TheBrooks** [comment]
I see the current providers are a drop down in this mock up.  
Is there a place where we can get this data of all the providers and their phone/email?

**Comment by JasminBarco** [comment]
here's a list of licensed hauler in Denver: https://www.denvergov.org/content/denvergov/en/trash-and-recycling/resources/hauler-licensing.html 

There are a lot though! I wonder if it's best to just reference this webpage on the site instead of adding providing hauler dropdown.
