### ISSUE TITLE
Merge Manager Resources and Property Owner Resources

### ISSUE THREAD

**Issue by JasminBarco** [codefordenver/Circular#303]
When I click under the Tools tab, I see "Property Manager Resources". This page  merges "Tips for purchasing service" and "going through the bid process"with FAQ's (my tenants requested service, now what? What if I don't have space for a dumpster?, I'm worried my tenants won't use the services right).

**Comment by TheBrooks** [comment]
I am unsure what you want done for this issue.

**Comment by ximsce** [comment]
@JasminBarco says this is done
