### ISSUE TITLE
My Campaign Navbar Link

### ISSUE THREAD

**Issue by TheBrooks** [codefordenver/Circular#317]
what should happen: upon click 'my campaign' page the user is redirected to the campaign they have signed.  For MVP a if a user can only have 1 signatured campaign and it redirects to that specific campaign.  The user can then remove their signature if they wish to sign a different campaign.

**Comment by hoop71** [comment]
@TheBrooks The Navbar is ready to accept this change. I'm sure you are working on the user model to attach a campaign to their account

**Comment by hoop71** [comment]
Accidently closed this issue. Reopened and reassigned to @TheBrooks
