### ISSUE TITLE
MapCard.js should display only one marker of Current Campaign 

### ISSUE THREAD

**Issue by hoop71** [codefordenver/Circular#325]
Map current displays markers for all campaigns and allows the user to click through them. We want to limit this to one single campaign, the one for which the user has registered.

**Comment by TheBrooks** [comment]
We need to have a discussion with @ximsce and @JasminBarco what we want the expected behavior for the map on the campaign page to be (for MVP and for after).  

It looks like issue #322 wants the opposite of this issue.
