### ISSUE TITLE
Add Login/Log out option to navbar

### ISSUE THREAD

**Issue by TheBrooks** [codefordenver/Circular#327]
what happens now: user has to go to a campaign page(any) to log in

What should happen: the navbar should have 2 state. a logged in and a logged out state.

If the user is logged out the 4th tab on the navbar is 'log in/sign in'
- upon click a dropdown is opened showing sign in with facebook and sign in with google options (this is nice because we wont have to create and style a whole sign in page)

if the user is logged in/once the user logs in the 4th link on the navbar is 'my campaign'.

**Comment by hoop71** [comment]
Added in Auth and Login / Logout function to the nav. Not as familiar with Redux operations but it works. Would love an eye on this.

There is also a note in travis for a backend passport issue. "OAuth2Strategy requires a clientID option" Seems like this could be do to environmental variables.

Cheers,
