### ISSUE TITLE
Update to React Router 4 & Use React-Router-Bootstrap

### ISSUE THREAD

**Issue by hoop71** [codefordenver/Circular#353]
Upgrade from 3 > 4. This one is gonna take some effort!

Define out Containers more appropriately. 
Refactor Components inside of new Containers. 
Define Routes according to new Structure.

**Comment by ximsce** [comment]
we should get base automated testing into place before attempting major technical refactoring.

**Comment by hoop71** [comment]
@t-laird  can we close this ticket?

**Comment by JasminBarco** [comment]
Check to see if this is merged in the master

**Comment by JasminBarco** [comment]
USER BEWARE!
