### ISSUE TITLE
Auto-populate Optional Info page-2

### ISSUE THREAD

**Issue by JasminBarco** [codefordenver/Circular#357]
I can search for my current waste collection provider and select on its name. Phone and email will be auto-populated. 

There is an Asterisk next to "waste collection provider", when I hover over it, it tells me how I can find out who my current provider is. 

All I have to do is go to where I take my trash and see which logo is on the bin. They will most often say size too. There should be an area where they can jot down that information. How many trash bins does your complex have? How big is each bin? What is the bin used for?

**Comment by JasminBarco** [comment]
Table for Waste Providers already exists, data needs to be pushed to production

**Comment by hoop71** [comment]
@JasminBarco We should have a chat about how you want to collect the trash bin info and how detailed you want it to be.
