### ISSUE TITLE
Move Optional Info page- build out welcome to your campaign page

### ISSUE THREAD

**Issue by JasminBarco** [codefordenver/Circular#358]
What I see now: I create a campaign, add it's campaign name. I'm then taken to the "optional info" page. I don't know what to fill out so I click next. I'm taken to an "activate your campaign" button.

What I want to see: I create a campaign, then get a congratulations! You've activated your campaign! (page or pop-up). 
Here's how you can use the "Tools for your Campaign"
- print a flier "Yes we Can"
- gather signatures manually (Print this Doc) 
- Share via social media

Tell us about your property (link to optional property info)

**Comment by hoop71** [comment]
This is ready to go. We need to build out the "Print This Doc" functionality for this feature. I will make a new issue for this.
