### ISSUE TITLE
Facebook API Updates Needed by 1 Aug

### ISSUE THREAD

**Issue by scottfirestone** [codefordenver/Circular#363]
Received this email for our Facebook (oauth) apps:	
 
App Review required by August 1, 2018 to retain existing permissions and features
 
 
The Facebook App Review process and API permissions model have been updated. Learn More.

In order to maintain your current API access, your app will need to be submitted for review by August 1, 2018. If your app is not submitted for review, you will lose access to these permissions and features.

user_friends

user_link

user_gender

user_age_range

The Facebook Platform APIs have been updated with these changes. Please review the FAQ to ensure you request the correct permissions and features with your app review submission.

If access to the permissions and features is approved, the app may need to be associated to a verified business to complete App Review.

**Comment by ximsce** [comment]
my guess is that we aren't using any of those particular permissions, so my hope is that we don't need to make any particular updates for our app or submit it for review. If we are requesting those permissions we should probably stop.

**Comment by scottfirestone** [comment]
@ximsce You're correct: we're only requesting `facebookId`, `name`, and `email`. Going to close this issue.
