### ISSUE TITLE
Epic: Campaign Page optional information

### ISSUE THREAD

**Issue by ximsce** [codefordenver/Circular#365]
As an apartment dweller I want to edit property owner and other optional information from the campaign page so that I can research that information after starting the campaign.

Assumption:
* Anyone who has signed campaign can edit optional info

parent of #359, parent of #358, parent of #357

**Comment by hoop71** [comment]
Chrome / Google  has some new standards for adding AutoPopulate input fields. Most of our users use Chrome so it's a good idea and would clear tons of console errors. 

https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#autofilling-form-controls:-the-autocomplete-attribute

**Comment by hoop71** [comment]
What are the goals with #369? A campaigns map is available on the home page. What do we seek to accomplish by putting this on the campaign page? Do we want to have this functionality in two places.

**Comment by hoop71** [comment]
#358 is ready with new ticket of #380 to create new collect manual signatures flier
