### ISSUE TITLE
remove .env.prod file from repo

### ISSUE THREAD

**Issue by ximsce** [codefordenver/Circular#368]
The .env.prod file includes private keys and should not have been added to github by following these instructions: https://help.github.com/articles/removing-sensitive-data-from-a-repository/

**Comment by hoop71** [comment]
Looks like we can knock this out when we get all the PRs closed out. It's gonna be a bit of a pain so let's get organized together before we do this. 

https://help.github.com/articles/removing-sensitive-data-from-a-repository/

**Comment by hoop71** [comment]
Opened a PR for deletion from Master. Steps above will delete it from the history as well
