### ISSUE TITLE
Spike: Email providers

### ISSUE THREAD

**Issue by ximsce** [codefordenver/Circular#371]
Investigate email providers so we don't have to run our own mail server.

Possible providers:
* sendgrid
* mailchimp
* google cloud provider?
* other options?

Acceptance Criteria:
* initial free tier for dev
* free or extremely cheap tier for non-profits
* can be called from a backend service (no mail server required)

**Comment by ximsce** [comment]
must integrate with constant contact or salsa engage

**Comment by JasminBarco** [comment]
duplicate
