### ISSUE TITLE
Setup Dev DB Environments in Firebase

### ISSUE THREAD

**Issue by hoop71** [codefordenver/Circular#383]
We need to structure out how to handle Dev, Staging and Prod environments. How to handle and wipe data and how many dbs we need.

Acceptance Criteria:

- dev database can be wiped with yarn command
- dev database can be seeded with test campaigns and signatures
- prod database can be wiped & initialized in a manual fashion (not sure how to auth this through the central setup)

**Comment by JasminBarco** [comment]
to discuss on monday, 9/17
maybe this is why Travis keeps breaking?
