### ISSUE TITLE
Firestore store cloud DB rules

### ISSUE THREAD

**Issue by hoop71** [codefordenver/Circular#384]
Establish DB rules for Campaign Creation, Sign Campaign and Edit Campaigns.

Assumptions: 
Users and only create one campaign and must be signed in to create a campaign
Only "admins" can update/edit campaigns
Users must be signed in to sign campaign, can only sign one campaign

Reference: https://firebase.google.com/docs/firestore/security/get-started

**Comment by JasminBarco** [comment]
This will fix security issues.
