### ISSUE TITLE
We found some campaigns page

### ISSUE THREAD

**Issue by katiescruggs** [codefordenver/Circular#391]
child of #389

wireframe page 4/11
Add a sorting option to this feature for simplicity when there are many campaigns.

**Comment by lalunamel** [comment]
I'm not a collaborator on this repo, but for the time being I **I claim this issue**

**Comment by hoop71** [comment]
@lalunamel I have some thoughts around how to accomplish this with Firestore. Doesn't appear there are native geo queriers yet but a good resource in the meantime. 
https://stackoverflow.com/questions/46553682/is-there-a-way-to-use-geofire-with-firestore

**Comment by lalunamel** [comment]
Hi @hoop71, thanks for the info!
I worked on this issue for National Day of Civic Hacking but didn't get much work done being in a new codebase and all. (Any work that was done should be on a PR/branch)
With that said, I don't think I'll have time to continue contributing, so unfortunately, **I give up this issue**.

**Comment by hoop71** [comment]
OK Thanks for your help and come back soon!
