### ISSUE TITLE
Solve Google Maps API Bug.

### ISSUE THREAD

**Issue by hoop71** [codefordenver/Circular#401]
error message when visiting CampaignPage: 'You have included the Google Maps JavaScript API multiple times on this page. This may cause unexpected errors.'

**Comment by dwhite96** [comment]
Sorry, didn't mean to close this issue so I reopened it. I couldn't duplicate this error.

**Comment by hoop71** [comment]
@dwhite96 so if you navigate to a campaign page, open the console and see if you see this error?
[Uploading Screen Shot 2018-08-15 at 14.40.13.png...]

**Comment by hoop71** [comment]
Might be some good support here: https://github.com/tomchentw/react-google-maps/issues/812

**Comment by dwhite96** [comment]
Yeah, I've dealt with this issue on multiple apps in the past. Can't remember how I solved it though. I'll take a look.

**Comment by JasminBarco** [comment]
@dwhite96 any progress??

**Comment by JasminBarco** [comment]
Thanks for closing a bunch of these requests, @hoop71! 
Let me know if there's anything else needed? New number and email- 720-910-1377; jasmin.barco@gmail.com
