### ISSUE TITLE
Using the calculator

### ISSUE THREAD

**Issue by chompasina** [codefordenver/Circular#41]
As a landlord 
when I click on a building's existing campaign page
I can enter how many units I have
and how much space I have for a receptacle
I hit calculate and see a price of recycling for my building

**Comment by ScorchConway** [comment]
The basic features are done on this calculator.  Currently you can enter a number for units, which populates a table of how many containers of various sizes you would need.  Currently missing is how much area each receptacle would take up, and also missing is any details on pricing.

**Comment by JasminBarco** [comment]
The calculator may be obsolete now...
