### ISSUE TITLE
Build out Property Owner FAQ page

### ISSUE THREAD

**Issue by chompasina** [codefordenver/Circular#44]
As a property owner
when I click on FAQ on the homepage
I see a list of Questions which can be clicked to expand the answers beneath that particular question

**Comment by JasminBarco** [comment]
Q: My tenants have requested service, now what? 
A: Check your current waste contract. Do they offer recycling services? Ask about how much it would cost to get the service for your property. You can always shop around for different haulers that offer recycling services in your area. See a list of registered haulers here: http://www.denvergov.org/content/denvergov/en/trash-and-recycling/recycling/business-and-multi-family-recycling.html 

Q:  What if I don't have space for a recycling dumpster? 
A: You can switch out a trash dumpster for a recycling dumpster. The amount of waste will not increase nor decrease, it will stay the same. What will change is which dumpster the materials are going in, recycle or trash. 

If there is no room in the enclosure, or you're not willing to give up a trash dumpster,  are your tenants willing to give up an extra parking space to make room for a recycling area? 

If you have trash chutes, make sure to tell your tenants where they can find their new recycling services. 

Whatever the case is, increase transparency by telling your tenants your logistical issues so they can understand your obstacles and hesitations if there are any. 

Q: I'm worried my tenants won't use the services right. 
A: Make sure your enclosures, bins and dumpsters are properly labeled! The bigger the sign, the better. If contamination is really a concern, provide your tenants with a recycle only enclosure so those who want to do the right thing  know where to go to do it.
