### ISSUE TITLE
Adding popup for a new address - Step 0

### ISSUE THREAD

**Issue by chompasina** [codefordenver/Circular#46]
As a user 
when I type in my new address on the homepage
I am taken to a page with a popup "You're the first to support recycling for your building!"
The popup has two buttons, "Okay! Let's do this" or "I want to learn more first"
If I click on "Okay!" then I see instructions within the popup on what information to fill in. 
After I click 'Continue' I see the normal address campaign page.

**Comment by ScorchConway** [comment]
As a trial, we're going to implement the modal over the home screen (rather than on the /apartments/id page) when the user hits Submit.

**Comment by robsedivy** [comment]
We can keep the modal over the home page.
