### ISSUE TITLE
A property page has Sharing capability

### ISSUE THREAD

**Issue by chompasina** [codefordenver/Circular#49]
As a user
when I am on a property campaign page
I can click to share with Facebook.
I can click to support with my google account.
I can click to support with my facebook account.

**Comment by TheBrooks** [comment]
Got the Facebook and twitter Share but not sure about 'text a link' share

Do you have any suggestions on how the "Text a Link" button will work when on a laptop?  Do you know of any services we can use to send out texts?

**Comment by TheBrooks** [comment]
Talked with @JasminBarco today.  We decided that a better use for the space is to replace 'Send a Text' with the 'download a flier' link.  

We believe that few people will have their neighbors phones numbers and it is easier for them to spread the word by posting flier in their complex or going door to door to pass them out.
