### ISSUE TITLE
Research Potential Partners

### ISSUE THREAD

**Issue by greglawless** [codefordenver/Circular#5]
### Research Potential Partners
- Teams should identify at least two potential project partners.
- Potential partners should be non-profit, government, or quasi-governmental organizations, community-based organizations or other community groups or organizations consistent with the CfD mission.
  Teams should identify if the initial idea is consistent with potential partner organization mission and goals.
- Teams should be able to clearly identify how potential partners could used the built solution, how they would maintain the end product and partners overall role in the built solution product live cycle.

**Comment by charlottello** [comment]
Working with EcoCycle in Boulder for development.
