### ISSUE TITLE
Add Facebook & google oauth

### ISSUE THREAD

**Issue by chompasina** [codefordenver/Circular#50]
As a user on a property campaign page,
I can click to login with Facebook.
Upon consent, my first name, last name and email address will be filled in, 
and I can still enter an optional note.

**Comment by MTempleman** [comment]
Pretty sure I've got everything working here save for the optional note.

**Comment by ximsce** [comment]
this task was completed in ruby module, but needs to be rewritten for the new react front-end.  something like react-facebook-login should work
