### ISSUE TITLE
add the "Download a Flyer" capability

### ISSUE THREAD

**Issue by robsedivy** [codefordenver/Circular#57]
A link on the property page will allow users to download a PDF advertisement for their building's recycling campaign. The PDF template with pull in identifying information for the building (name/address) and serve as an advertisement that can be posted in the common area of the building.

**Comment by JasminBarco** [comment]
Eco-Cycle wants to see the MVP first to know how to style the flier

**Comment by JasminBarco** [comment]
see issue #276

**Comment by JasminBarco** [comment]
Placeholder
[CodeforDenver_Flier.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/584619e37a5c7e1300b983de/125516c66e82c728ace21e0d46cb9b9e26848cbbabecb155a14fcfb2254f22616b48e13b628ae92dbc56395b4d5a49ff450c0b42f8f8da78a4be35718e5c0be5d23c5775cf2f0dbefad341eb5ee779c11ac7a4b6984dc8e23c20e6828c4a3e1f031c8ff65b27ed.pdf)
