### ISSUE TITLE
Brainstorm solutions

### ISSUE THREAD

**Issue by greglawless** [codefordenver/Circular#7]
### Brainstorm Solutions
- [ ] Using a [timer](https://www.google.com/#q=timer), take 5 minutes to write down as many rough ideas on sticky notes as you can.
- [ ] Go around as a team and put your sticky notes on a wall as you say what you wrote.
- [ ] Group similar ideas together.

When you're finished, you're ready to move on to creating paper prototypes!

![screen shot 2016-01-28 at 4 25 30 pm](https://cloud.githubusercontent.com/assets/100216/12662189/d40df98c-c5db-11e5-9517-e3d613a904b9.png)

**Comment by charlottello** [comment]
Project scope has been determined to focus on recycling practices in residential housing in Denver.  Topic Closed.
