### ISSUE TITLE
build out landing page container/component

### ISSUE THREAD

**Issue by Casey1449** [codefordenver/Circular#93]
When I land on the homepage, I expect to see a full page of attractive and mobile-responsive content below the hero section.

COA:
- Create the section with the explanatory step-by-step icons, and implement mobile-first styling.
- Create the section with Denver recycling info, and implement mobile-first styling.
- Create the section with nav links for property managers, and implement mobile-first styling, and wire those links to their appropriate skeleton pages.

**Comment by scottfirestone** [comment]
Note: Split into issues 142, 143, and 144.
